source "https://rubygems.org"
gem 'sinatra', '1.1.0'
gem 'mandrill'
gem 'thin'
gem 'mongo'
gem 'bson_ext'
gem 'json'
gem 'sinatra-reloader'
gem 'mongoid'
gem 'bson'
gem 'monkey-lib'
gem 'sinatra-sugar'
gem 'rest-client'